[book]
authors = ["Mario Reder <mario.reder@pm.me>"]
language = "en"
multilingual = false
src = "src"
title = "Shroom Kingdom Whitepaper"
git-repository-url = "https://github.com/Shroom-Kingdom"
cname = "whitepaper.shroomkingdom.net"

[output.html]
default-theme = "ayu"
additional-js = ["src/js/plausible.js"]
additional-css = ["src/css/main.css"]
